### ISSUE TITLE
Windows_exporter stop working  on some servers

### ISSUE THREAD

**Issue by zenzedoon** [prometheus-community/windows_exporter#950] opened 2022-03-02 09:11 UTC
Windows_exporter v18.1 service stop working when there are hight usage of CPU or RAM and can't restart automatically , it need to be restarted manually every time .
i tested with some early version (v16 and v17) and i got the same issue, 
The issue is happned in several servers .
![image](https://user-images.githubusercontent.com/50891244/156330449-57bd9c4f-d5d0-4f15-9037-7061eebdacc6.png)
![image](https://user-images.githubusercontent.com/50891244/156330532-c51eb58b-e5b1-423e-956b-5dd3859eaf8f.png)
![image](https://user-images.githubusercontent.com/50891244/156330754-d121ebe0-2c0b-4d05-a869-44fd1998296f.png)

**Comment by cyayon** [comment] 2022-03-04 14:43
Hello,

Same issue here on windows 2019 servers.

**Comment by cyayon** [comment] 2022-03-11 09:23
it happens every 3-5 days on all azure Windows 2019 servers.
ENABLED_COLLECTORS=process,os,cpu,cs,logical_disk,net,service,system,tcp

trying 0.17.1 version and see if it happens again.

**Comment by zenzedoon** [comment] 2022-03-11 09:42
Thanks @cyayon  for your respond , for me the issue happen on multiple VMs on Vcenter , and exactly when they have a huge consumption of CPU or Memory ,

**Comment by breed808** [comment] 2022-03-13 03:01
Duplicate of #794

**Closed by breed808** 2022-03-13 03:01 UTC
