### ISSUE TITLE
Windows 2008 32-bit can not run windows_exporter - 0.19.0-386. exe

### ISSUE THREAD

**Issue by renziyou** [prometheus-community/windows_exporter#1048] opened 2022-08-25 10:14 UTC
Windows 2008 32-bit can not run windows_exporter - 0.19.0-386. exe

**Comment by breed808** [comment] 2022-08-26 08:40
Duplicate of #1044, let's keep the discussion there.

**Closed by breed808** 2022-08-26 08:40 UTC
Labels: duplicate
