### ISSUE TITLE
Provide Helm chart for Windows nodes in Kubernetes deployments

### ISSUE THREAD

**Issue by aidapsibr** [prometheus-community/windows_exporter#578] opened 2020-07-27 01:47 UTC
With Windows nodes now supported in Kubernetes it would be really helpful to get the low-level metrics this provides.

**Comment by chzbrgr71** [comment] 2020-07-30 23:11
I got a working container/daemonSet for K8s. I have the exporter running on Windows, but I still need to figure out how to get it integrated into the Prom service overall. 

I'm planning to submit a PR shortly.

**Comment by iusergii** [comment] 2020-08-04 15:01
Also, looking forward to it.

**Comment by chzbrgr71** [comment] 2020-08-04 15:50
This is my PR. It still needs work, but it's a start https://github.com/prometheus-community/windows_exporter/pull/581

**Comment by carlpett** [comment] 2020-08-26 06:46
I'll close this as a duplicate of #546.

**Closed by carlpett** 2020-08-26 06:46 UTC

**Comment by DerrickMartinez** [comment] 2020-11-05 19:33
I don't think you can just run this inside a container. Typically you'd want to proxy through wins.exe
