### ISSUE TITLE
Incorrect metric collection for "windows_iis*" from PerfLib on IIS collector

### ISSUE THREAD

**Issue by FeelProud** [prometheus-community/windows_exporter#1132] opened 2023-02-03 16:47 UTC
Hello,

I'm facing an interesting issue when I'm enabling the IIS collector to collect metrics from my websites.

# Problem
Here is the multiple errors I can find on my metric page : 

```
An error has occurred while serving metrics:

37 error(s) occurred:
* collected metric "windows_iis_current_anonymous_users" { label:<name:"site" value:"www.mywebsite.com" > gauge:<value:1 > } was collected before with the same name and label values
* collected metric "windows_iis_current_blocked_async_io_requests" { label:<name:"site" value:"www.mywebsite.com" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_current_cgi_requests" { label:<name:"site" value:"www.mywebsite.com" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_current_connections" { label:<name:"site" value:"www.mywebsite.com" > gauge:<value:6 > } was collected before with the same name and label values
...
```

The debug mode gave me no clues from where the error was coming, so I decided to investigate.

# Solution
The error seems to be provoked because a website can have an "#" sign in his name.
You can use the following Powershell command to list the existing values : 

```Powershell
# Load the required modules
Import-Module WebAdministration

# Get the performance counters for the IIS web service
$counterSet = Get-Counter -Counter "\Web Service(*)\*"

# Loop through each counter and display the counter path and value
foreach ($counter in $counterSet) {
    Write-Host "$($counter.CounterPath) = $($counter.CounterSampleValue)"
}
```

or just go in the performance monitor : 

![image](https://user-images.githubusercontent.com/21657978/216658377-568ac9d5-4927-4a3e-829f-becc5f57f4d1.png)

This is definitely the origin of the problem because only these websites are triggering errors.

There is no regex used in the IIS collector to remove the "#" sign, so error seems to come from `collector.go` file.

**Comment by breed808** [comment] 2023-02-04 01:51
Duplicate of  #1009

**Closed by breed808** 2023-02-04 01:51 UTC
Labels: duplicate
