### ISSUE TITLE
Windows IIS Collector Fails

### ISSUE THREAD

**Issue by kbick675** [prometheus-community/windows_exporter#1049] opened 2022-08-25 13:47 UTC
We have several servers where IIS metric collection throws errors. This occurs with both v0.18.1 and v0.19.0. The most recent issue involves a server where a site was stopped, but I'm not 100% sure whether all servers affected have stopped or deleted sites. 

These are all Server 2016.

Different sites across different pools, but largely they follow the same count of errors:

```
An error has occurred while serving metrics: 36 error(s) occurred: 

* collected metric "windows_iis_current_anonymous_users" { label:<name:"site" value:"RouterService" > gauge:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_current_blocked_async_io_requests" { label:<name:"site" value:"RouterService" > gauge:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_current_cgi_requests" { label:<name:"site" value:"RouterService" > gauge:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_current_connections" { label:<name:"site" value:"RouterService" > gauge:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_current_isapi_extension_requests" { label:<name:"site" value:"RouterService" > gauge:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_current_non_anonymous_users" { label:<name:"site" value:"RouterService" > gauge:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_received_bytes_total" { label:<name:"site" value:"RouterService" > counter:<value:1.216608299e+09 > } was collected before with the same name and label values 
* collected metric "windows_iis_sent_bytes_total" { label:<name:"site" value:"RouterService" > counter:<value:6.465130012e+09 > } was collected before with the same name and label values 
* collected metric "windows_iis_anonymous_users_total" { label:<name:"site" value:"RouterService" > counter:<value:7.256635e+06 > } was collected before with the same name and label values 
* collected metric "windows_iis_blocked_async_io_requests_total" { label:<name:"site" value:"RouterService" > counter:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_cgi_requests_total" { label:<name:"site" value:"RouterService" > counter:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_connection_attempts_all_instances_total" { label:<name:"site" value:"RouterService" > counter:<value:6.640008e+06 > } was collected before with the same name and label values 
* collected metric "windows_iis_files_received_total" { label:<name:"site" value:"RouterService" > counter:<value:7418 > } was collected before with the same name and label values 
* collected metric "windows_iis_files_sent_total" { label:<name:"site" value:"RouterService" > counter:<value:7496 > } was collected before with the same name and label values 
* collected metric "windows_iis_ipapi_extension_requests_total" { label:<name:"site" value:"RouterService" > counter:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_locked_errors_total" { label:<name:"site" value:"RouterService" > counter:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_logon_attempts_total" { label:<name:"site" value:"RouterService" > counter:<value:7.256635e+06 > } was collected before with the same name and label values 
* collected metric "windows_iis_non_anonymous_users_total" { label:<name:"site" value:"RouterService" > counter:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_not_found_errors_total" { label:<name:"site" value:"RouterService" > counter:<value:948584 > } was collected before with the same name and label values 
* collected metric "windows_iis_rejected_async_io_requests_total" { label:<name:"site" value:"RouterService" > counter:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"other" > label:<name:"site" value:"RouterService" > counter:<value:841 > } was collected before with the same name and label values 
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"COPY" > label:<name:"site" value:"RouterService" > counter:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"DELETE" > label:<name:"site" value:"RouterService" > counter:<value:59 > } was collected before with the same name and label values 
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"GET" > label:<name:"site" value:"RouterService" > counter:<value:7.236717e+06 > } was collected before with the same name and label values 
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"HEAD" > label:<name:"site" value:"RouterService" > counter:<value:605 > } was collected before with the same name and label values 
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"LOCK" > label:<name:"site" value:"RouterService" > counter:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"MKCOL" > label:<name:"site" value:"RouterService" > counter:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"MOVE" > label:<name:"site" value:"RouterService" > counter:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"OPTIONS" > label:<name:"site" value:"RouterService" > counter:<value:206 > } was collected before with the same name and label values 
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"POST" > label:<name:"site" value:"RouterService" > counter:<value:18244 > } was collected before with the same name and label values 
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"PROPFIND" > label:<name:"site" value:"RouterService" > counter:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"PROPPATCH" > label:<name:"site" value:"RouterService" > counter:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"PUT" > label:<name:"site" value:"RouterService" > counter:<value:7418 > } was collected before with the same name and label values 
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"SEARCH" > label:<name:"site" value:"RouterService" > counter:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"TRACE" > label:<name:"site" value:"RouterService" > counter:<value:0 > } was collected before with the same name and label values 
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"UNLOCK" > label:<name:"site" value:"RouterService" > counter:<value:0 > } was collected before with the same name and label values

```

**Comment by kbick675** [comment] 2022-08-25 22:25
Adding that on at least one pair of servers, I added the Default Web Site back to the server config with it stopped, and the issue went away.

**Comment by breed808** [comment] 2022-09-23 21:02
Duplicate of #1009 

@kbick675 could you review the troubleshooting steps listed in that thread and let me know you find? I'd be particularly interested to see if the metrics returned by `Get-Counter` change after the Default Web Site is removed.

**Closed by breed808** 2022-09-23 21:02 UTC
Labels: bug, duplicate, collector/iis
