### ISSUE TITLE
45 Sek. of data on all collectors is lost on CPU spikes

### ISSUE THREAD

**Issue by FLeven** [prometheus-community/windows_exporter#204] opened 2018-05-22 06:56 UTC
If one of the machines running WMI_Exporter gets a little higher CPU demand then usual, the monitoring data for all collectors for about 45 seconds is lost.

**Comment by carlpett** [comment] 2018-05-22 07:06
This sounds like a duplicate of #190? This is not related to wmi_exporter itself, but rather process scheduling in the operating system. If the machine is overloaded, then the exporter will not necessarily be given an opportunity to respond to the scrape request. Or, even if it is able to start doing so, a number of cross-process calls to the WMI subsystem must also be scheduled.

**Comment by FLeven** [comment] 2018-05-22 07:16
Even if the server gets a 60% load on 1 of 4 cores only, it stops collecting data. If a server gets slowly to a 60% load over a longer time priod, everythins is fine.

**Comment by carlpett** [comment] 2018-05-22 07:21
Does the `up` metric created by the Prometheus server become 0 at these times?

**Comment by FLeven** [comment] 2018-05-22 07:33
No, I will get an alert, if UP changes to 0  on one of my prom jobs.

**Comment by carlpett** [comment] 2018-05-22 07:45
Does your alert trigger instantaneously (ie does not have a `for` clause)? Hm, so Prometheus does not see the scrape as failed? This is very strange. What about the `wmi_exporter_collector_success` metric, what does it say during these times?

**Comment by FLeven** [comment] 2018-05-22 07:49
Ok, this is **not** related to the cpu, but abobe 2.5K of **threads** on a system, I run into this problem.

I will look into the "wmi_exporter_collector_success" metric soon.

**Comment by FLeven** [comment] 2018-05-22 09:17
It is always "1"

**Comment by carlpett** [comment] 2018-05-22 09:44
For all collectors? But they still don't report any data from the collectors?
Could you try a query like `count({job="wmi_exporter", instance="<name/ip of host with problem>"})` and see if it goes down when you have the problems?

**Comment by FLeven** [comment] 2018-05-22 09:48
Yes, and I believe there is no data to report, because collecting on the server just stops above the "threads" threshhold. Ok, I will try to get more infos.

**Comment by carlpett** [comment] 2018-05-22 16:36
Is 45 sec your scrape interval? Or is it lower, but the lack of data is still exactly 45 seconds? This also seems very odd.
And `wmi_exporter_collector_success` is 1 for all labels at this time? What about `wmi_exporter_collector_duration_seconds`, how long time do these scrapes take? Anything written to the Windows event log?

**Comment by FLeven** [comment] 2018-05-25 08:47
1. yes, 30 sek + 10 sec. timeout
2. There is no data, also no wmi_exporter_collector_success
3. 2-5 sec.
4. Nothing of interest in the WinEventlog

Almost all target are Terminal Server/RDS

**Comment by carlpett** [comment] 2018-06-06 08:51
Ok, so the fact that you get no data at all would indicate that Prometheus cancels the scrape due to timeout. Could you verify this by checking if `up` is actually 1 at these times?
It's hard to guess at exactly what is happening, but if you have sudden bursts of high thread counts, it could be a contention issue which causes the exporter (or the underlying wmi system) to not get the cycles needed to complete in time.
We currently don't keep track of if the client (Prometheus in this case) cancels the request. This might be something to add to be able to log when it happens, at least.

But please check the graph view of your Prometheus server to validate that `up` over one of these periods.

**Comment by FLeven** [comment] 2018-06-12 07:13
I checked it again and it is UP, and if UP = 0 it is not releated to the missing monitoring data, because there is a time difference from xx minutes to hours.

**Comment by FLeven** [comment] 2018-06-14 10:13
I slimed down the collector to "cs,os" only and it works without problems.

**Comment by FLeven** [comment] 2018-06-14 16:47
"cs,os,services" (selecting 5 services), is also fine. Adding only one of the other collectors, will lead to lost data.

**Comment by carlpett** [comment] 2018-06-17 21:17
Very strange. I'm wondering if you may be seeing something like #89?

**Comment by FLeven** [comment] 2018-06-18 07:40
Yes, could be related, I also see the 16-17 minute pit of missing data. I believe it is related to some limits or internals of wmi, winmgmt and not to any stress / CPU spikes on the server, because you can clearly get around the problem by just selecting fewer collectors. 
I also tried to separate the "move the  WMI service to a stand alone host", but it does not change anything. I can also remember, when M$ started to offer monitoring with systemcenter back in the Day, there were similar issues, but I don't know if they managed to get around it.

**Closed** 2021-07-09 08:42 UTC
Labels: info needed, question
