### ISSUE TITLE
Windows Host Process Containers not being picked up in container metrics

### ISSUE THREAD

**Issue by BenHesketh21** [prometheus-community/windows_exporter#1128] opened 2023-01-26 11:42 UTC
I am running the windows_exporter as a host process container in K8s and currently it is not picking its own container related metrics as well as any other host process container metrics. I am running the 0.20.0-lts2022 container image version.

**Comment by breed808** [comment] 2023-02-04 01:23
I'm not able to test the exporter running in a k8s platform; does the documentation in https://github.com/prometheus-community/windows_exporter/tree/master/kubernetes assist at all?

**Comment by BenHesketh21** [comment] 2023-02-04 02:09
> I'm not able to test the exporter running in a k8s platform; does the documentation in https://github.com/prometheus-community/windows_exporter/tree/master/kubernetes assist at all?

I used that daemonset when running it in my cluster and it worked for me

**Comment by jsturtevant** [comment] 2023-03-22 16:07
Duplicate of https://github.com/prometheus-community/windows_exporter/issues/964. The main issue is outlined in https://github.com/prometheus-community/windows_exporter/issues/964#issuecomment-1095523596

**Closed** 2023-04-02 20:25 UTC
Labels: help wanted
