### ISSUE TITLE
IIS collector is broken on 0.17.0

### ISSUE THREAD

**Issue by zpf2022** [prometheus-community/windows_exporter#903] opened 2022-01-02 04:19 UTC
Hi,
windows_exporter  0.17.0 IIS collector is not working as expected.
Exporter is not displaying any metrics, only error message.
（windows 2012R2  IIS 8  /  windows 2016   IIS 10）
http://localhost:9182

windows_exporter
Metrics

(version=0.17.0, branch=master, revision=4d771d2bcedd4b29f0bf2bade1a45f5e0ee3198d)

An error has occurred while serving metrics:

11248 error(s) occurred:
* collected metric "windows_iis_worker_request_errors_total" { label:<name:"app" value:XXX" > label:<name:"pid" value:"5780" > label:<name:"status_code" value:"401" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_request_errors_total" { label:<name:"app" value:"XXX" > label:<name:"pid" value:"5780" > label:<name:"status_code" value:"403" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_request_errors_total" { label:<name:"app" value:"XXX" > label:<name:"pid" value:"5780" > label:<name:"status_code" value:"404" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_request_errors_total" { label:<name:"app" value:"XXX" > label:<name:"pid" value:"5780" > label:<name:"status_code" value:"500" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_current_websocket_requests" { label:<name:"app" value:"XXX" > label:<name:"pid" value:"5780" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_websocket_connection_attempts_total" { label:<name:"app" value:"XXX" > label:<name:"pid" value:"5780" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_websocket_connection_accepted_total" { label:<name:"app" value:"XXX" > label:<name:"pid" value:"5780" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "XXX" { label:<name:"app" value:"XXX" > label:<name:"pid" value:"5780" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_request_errors_total" { label:<name:"app" value:"XXX" > label:<name:"pid" value:"21708" > label:<name:"status_code" value:"401" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_request_errors_total" { label:<name:"app" value:"XXX" > label:<name:"pid" value:"21708" > label:<name:"status_code" value:"403" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_request_errors_total" { label:<name:"app" value:"XXX" > label:<name:"pid" value:"21708" > label:<name:"status_code" value:"404" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_request_errors_total" { label:<name:"app" value:"XXX" > label:<name:"pid" value:"21708" > label:<name:"status_code" value:"500" > counter:<value:0 > } was collected before with the same name and label values
*

**Comment by breed808** [comment] 2022-01-02 04:34
This sounds similar to the `textfile` collector bug in #899.

I'll see if I can reproduce this in a testing VM.

**Comment by breed808** [comment] 2022-01-02 10:37
I've not been able to reproduce this with a vanilla IIS setup. Could you provide details on your IIS worker configuration?

The debug output from the exporter (`--log.level=debug`) would be great if possible.

**Comment by zpf2022** [comment] 2022-01-02 14:03
![image](https://user-images.githubusercontent.com/96966733/147878271-a8e2e715-2003-455e-b1b0-d05a073df380.png)

**Comment by zpf2022** [comment] 2022-01-02 14:47
is working fine for 0.16.0

![image](https://user-images.githubusercontent.com/96966733/147879315-3467d426-12f9-413c-980b-9d84285c4501.png)

**Comment by FLeven** [comment] 2022-01-04 10:36
I had the same error, but only on a vm where IIS and Exchange collectors are enabled -> server 2016. I disabled IIS for now.
I also have vm's running server 2019 and the IIS collector is working fine.

**Comment by beckerr-MV** [comment] 2022-01-05 13:25
We have the same problem. attached our appeal:
--log.format logger:eventlog?name=windows_exporter --collectors.enabled cpu,cs,logical_disk,net,os,service,iis --telemetry.addr :9182   --collector.service.services-where="Name LIKE 'Tomcat%' OR Name LIKE 'Cerberus%'"

**Comment by breed808** [comment] 2022-01-08 03:34
I've had a look at the `iis` collector and it may be that the perflib source is returning duplicate entries, resulting in duplicate entries.

@zpf2022 could you provide the full error output for one of the metrics, so I can view the labels?

Also, are there any duplicate names in the IIS worker configuration? I feel I need to reproduce the issue before I can fix it.

**Comment by FLeven** [comment] 2022-01-10 09:05
`An error has occurred while serving metrics:

16 error(s) occurred:
* collected metric "windows_iis_worker_request_errors_total" { label:<name:"app" value:"DefaultAppPool" > label:<name:"pid" value:"3392" > label:<name:"status_code" value:"401" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_request_errors_total" { label:<name:"app" value:"DefaultAppPool" > label:<name:"pid" value:"3392" > label:<name:"status_code" value:"403" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_request_errors_total" { label:<name:"app" value:"DefaultAppPool" > label:<name:"pid" value:"3392" > label:<name:"status_code" value:"404" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_request_errors_total" { label:<name:"app" value:"DefaultAppPool" > label:<name:"pid" value:"3392" > label:<name:"status_code" value:"500" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_current_websocket_requests" { label:<name:"app" value:"DefaultAppPool" > label:<name:"pid" value:"3392" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_websocket_connection_attempts_total" { label:<name:"app" value:"DefaultAppPool" > label:<name:"pid" value:"3392" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_websocket_connection_accepted_total" { label:<name:"app" value:"DefaultAppPool" > label:<name:"pid" value:"3392" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_websocket_connection_rejected_total" { label:<name:"app" value:"DefaultAppPool" > label:<name:"pid" value:"3392" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_request_errors_total" { label:<name:"app" value:"WsusPool" > label:<name:"pid" value:"1484" > label:<name:"status_code" value:"401" > counter:<value:5 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_request_errors_total" { label:<name:"app" value:"WsusPool" > label:<name:"pid" value:"1484" > label:<name:"status_code" value:"403" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_request_errors_total" { label:<name:"app" value:"WsusPool" > label:<name:"pid" value:"1484" > label:<name:"status_code" value:"404" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_request_errors_total" { label:<name:"app" value:"WsusPool" > label:<name:"pid" value:"1484" > label:<name:"status_code" value:"500" > counter:<value:63 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_current_websocket_requests" { label:<name:"app" value:"WsusPool" > label:<name:"pid" value:"1484" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_websocket_connection_attempts_total" { label:<name:"app" value:"WsusPool" > label:<name:"pid" value:"1484" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_websocket_connection_accepted_total" { label:<name:"app" value:"WsusPool" > label:<name:"pid" value:"1484" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_worker_websocket_connection_rejected_total" { label:<name:"app" value:"WsusPool" > label:<name:"pid" value:"1484" > counter:<value:0 > } was collected before with the same name and label values

`

**Comment by zpf2022** [comment] 2022-01-10 09:32
is working fine for only one site:
![1](https://user-images.githubusercontent.com/96966733/148744016-c109f6ac-89d0-4c9b-af39-77b04d653558.png)

![2](https://user-images.githubusercontent.com/96966733/148744028-3bc47680-7e6a-48ae-bfd9-e6b849a32b58.png)

**Comment by linuxauditor** [comment] 2022-01-10 11:14
> so, are there any duplicate names in the IIS worker configuration? I feel I need to reproduce the issue before I can fix it.

This is not possible with IIS. It will not allow you to create vsites with the same name...

**Comment by mucahidk** [comment] 2022-01-12 10:50
Is there a solution similar to the one here? 

https://github.com/prometheus-community/postgres_exporter/issues/219

**Comment by linuxauditor** [comment] 2022-01-12 11:06
> Is there a solution similar to the one here?
> 
> [prometheus-community/postgres_exporter#219](https://github.com/prometheus-community/postgres_exporter/issues/219)

Hmmm I don't think so. Looks like that was related to some misconfiguration on the exporter's config. They added some "group by query" and that removed the duplicates.

**Comment by linuxauditor** [comment] 2022-01-12 11:07
I think that this is however related to this. Too big of a coincidence that the exact metrics mentioned here are the **only ones** that we are seeing as being duplicated:

https://github.com/prometheus-community/windows_exporter/pull/887

**Comment by mucahidk** [comment] 2022-01-12 11:22
> I think that this is however related to this. Too big of a coincidence that the exact metrics mentioned here are the **only ones** that we are seeing as being duplicated:
> 
> #887
yes i think you are right, i hope it gets fixed.

**Comment by linuxauditor** [comment] 2022-01-12 11:23
I would guess the issue is here. Looks there is if statement where IIS is greater or equal to v8:

https://github.com/prometheus-community/windows_exporter/blob/ce205d4c4d7e20b473897fb367e057e08542a6a6/collector/iis.go#L1577

This would explain why we are having issues with v8 and v10

**Comment by safster123** [comment] 2022-01-18 12:25
Just wanted to note that I'm also seeing the same issue after attempting to upgrade from 0.16.0 to 0.17.1.

Downgraded back to 0.16.0 and the problem no longer occurs.

**Comment by cubakid** [comment] 2022-01-18 20:29
Using 0.17.1 with the IIS collector enabled /metrics returns a 500 error for me on Windows Server 2016.

The log doesn't show any errors or warnings when using debug level.

C:\Program Files\windows_exporter>windows_exporter.exe --log.level="debug" --telemetry.addr :9182 --config.file="C:\Program Files\windows_exporter\config.yml"
time="2022-01-18T15:23:49-05:00" level=info msg="Loading configuration file: C:\\Program Files\\windows_exporter\\config.yml" source="config.go:37"
time="2022-01-18T15:23:49-05:00" level=debug msg="Initializing SWbemServices" source="exporter.go:249"
time="2022-01-18T15:23:49-05:00" level=debug msg="Detected Windows version 6.300000\n" source="collector.go:48"
time="2022-01-18T15:23:49-05:00" level=debug msg="Detected IIS 10.0\n" source="iis.go:56"
time="2022-01-18T15:23:49-05:00" level=info msg="Enabled collectors: os, system, iis, cpu, cs, logical_disk, net" source="exporter.go:348"
time="2022-01-18T15:23:49-05:00" level=info msg="Starting windows_exporter (version=0.17.1, branch=heads/tags/v0.17.1, revision=d9f4264fc4ee183462fc23032ce9b60444411b87)" source="exporter.go:400"
time="2022-01-18T15:23:49-05:00" level=info msg="Build context (go=go1.17.5, user=runneradmin@fv-az177-480, date=20220102-09:24:12)" source="exporter.go:401"
time="2022-01-18T15:23:49-05:00" level=info msg="Starting server on :9182" source="exporter.go:404"
time="2022-01-18T15:23:49-05:00" level=info msg="TLS is disabled." source="gokit_adapter.go:38"
time="2022-01-18T15:24:31-05:00" level=debug msg="collector cs succeeded after 0.000999s." source="exporter.go:210"
time="2022-01-18T15:24:31-05:00" level=debug msg="collector system succeeded after 0.001001s." source="exporter.go:210"
time="2022-01-18T15:24:31-05:00" level=debug msg="collector net succeeded after 0.002000s." source="exporter.go:210"
time="2022-01-18T15:24:31-05:00" level=debug msg="collector cpu succeeded after 0.004000s." source="exporter.go:210"
time="2022-01-18T15:24:31-05:00" level=debug msg="collector logical_disk succeeded after 0.000000s." source="exporter.go:210"
time="2022-01-18T15:24:31-05:00" level=debug msg="collector iis succeeded after 0.005001s." source="exporter.go:210"
time="2022-01-18T15:24:31-05:00" level=debug msg="collector os succeeded after 0.012170s." source="exporter.go:210"
time="2022-01-18T15:24:31-05:00" level=debug msg="collector service succeeded after 0.410001s." source="exporter.go:210"

-----------------------------------------------------------------------------------------------------
That log was generated with...


PS C:\> curl -Uri http://localhost:9182/metrics
curl : The remote server returned an error: (500) Internal Server Error.
At line:1 char:1
+ curl -Uri http://localhost:9182/metrics
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

PS C:\>

**Comment by JDA88** [comment] 2022-01-26 16:27
Any idea if a version 0.17.2 can be release soon(tm) with this fix?

**Comment by breed808** [comment] 2022-01-26 20:25
Hopefully in the next week, there's a few prerequisite PRs that need to be merged before the next release.

**Comment by JDA88** [comment] 2022-01-26 23:00
> Hopefully in the next week, there's a few prerequisite PRs that need to be merged before the next release.

Great, as long as it's not in 2 month It's perfect, we want to implementing IIS monitoring on 200+ servers and I don’t want to go back to 0.16 as 0.17.1 is running much better.

**Comment by eliassal** [comment] 2022-01-28 15:49
Now it is happeneing even when I dont use the config file but use commandline arguments

**Closed** 2022-01-31 08:53 UTC
Labels: bug, collector/iis

**Comment by breed808** [comment] 2022-01-31 08:56
Fix has been merged. I'll have the v0.18.0 release created in the next 24-48 hours.

**Comment by eliassal** [comment] 2022-01-31 11:42
Great and thanks, how about the other issue I opened at the same time
https://github.com/prometheus-community/windows_exporter/issues/933
it is also annoying and not getting the worker process for webadmin for IIS in win 10
