### ISSUE TITLE
There is a typo in os collector on the "windows_os_process_memory_limit_bytes" metric

### ISSUE THREAD

**Issue by JDA88** [prometheus-community/windows_exporter#577] opened 2020-07-23 14:22 UTC
As title say it should be `windows_os_process_memory_limit_bytes` but it is showing as `windows_os_process_memory_limix_bytes` on the `/metric` page

To be extra clear:
limi**x** with an `x` instead of an `t`

**Comment by carlpett** [comment] 2020-07-25 18:24
Hey @JDA88,
This is a duplicate of #283, so I'll close this.

**Closed by carlpett** 2020-07-25 18:24 UTC
