### ISSUE TITLE
DHCP collector error serving metrics

### ISSUE THREAD

**Issue by elita26** [prometheus-community/windows_exporter#566] opened 2020-07-06 16:41 UTC
Hello
I have problem with dhcp collector, when i try serving metrics, i get in error
```
An error has occurred while serving metrics:

collected metric windows_dhcp_denied_due_to_match_total counter:<value:0 >  has help "Total number of DHCP requests denied, based on non-matches from the Allow list (DeniedDueToNonMatch)" but should have "Total number of DHCP requests denied, based on matches from the Deny list (DeniedDueToMatch)"
```
windows exporter version v0.13.0
Enabled_collector="os,dhcp,dns,cpu,cs,memory,net,system,tcp"
Windows server 2012 r2 datacenter with dhcp server
Windows event log is empty

**Comment by carlpett** [comment] 2020-07-07 06:54
This is a duplicate of #531.
It will be fixed in the next release!

**Closed by carlpett** 2020-07-07 06:54 UTC
Labels: bug, collector/dhcp
