### ISSUE TITLE
windows server 2012 R2 X64 install windows-exproter-0.14.0 error

### ISSUE THREAD

**Issue by xianxichao** [prometheus-community/windows_exporter#625] opened 2020-10-12 02:35 UTC
administrotr login
github download windows-exproter-0.14.0-386.msi  or windows_exporter-0.14.0-amd64.msi
tips   service windows_exporter failed to start 
verify that you have sufficient privileges to start system services

I tried to install other versions, and it's still the case
in anther OS，it 's OK

**Comment by carlpett** [comment] 2020-10-19 09:59
Duplicate of #627

**Closed by carlpett** 2020-10-19 09:59 UTC
