### ISSUE TITLE
Provide the windows_exporter as daemon-set

### ISSUE THREAD

**Issue by keikhara** [prometheus-community/windows_exporter#590] opened 2020-08-26 02:42 UTC
As many cloud providers are locking down and providing managed K8S, it would be great if you can make the executable for windows_export a daemon-set. It will help clients who wants to run prometheus on windows but does not require them to logon to the windows node.

**Comment by carlpett** [comment] 2020-08-26 06:50
Hi @keikhara,
This is a duplicate of #546.

**Closed by carlpett** 2020-08-26 06:50 UTC
