### ISSUE TITLE
failed collecting iis metrics:<nil> iis 状态正常，求解决方法！！！

### ISSUE THREAD

**Issue by Mrlinux-yyds** [prometheus-community/windows_exporter#1042] opened 2022-08-16 01:52 UTC
time="2022-08-16T09:47:51+08:00" level=error msg="failed collecting iis metrics:<nil> counter not found" source="iis.go:817"
time="2022-08-16T09:47:51+08:00" level=error msg="collector iis failed after 0.000000s: counter not found" source="exporter.go:209"
time="2022-08-16T09:48:11+08:00" level=error msg="failed collecting iis metrics:<nil> counter not found" source="iis.go:817"
time="2022-08-16T09:48:11+08:00" level=error msg="collector iis failed after 0.000000s: counter not found" source="exporter.go:209"

**Comment by Mrlinux-yyds** [comment] 2022-08-16 05:59
lodctr /r 已解决

**Comment by breed808** [comment] 2022-08-20 11:16
Hello, which version of the exporter are you running?

**Comment by DaveOHenry** [comment] 2022-09-22 21:33
Got the same problem multiple times a day since updating to 0.19.0. The CPU collector also fails.
We were running 0.16.0 before and never experienced this issue.

```
{"source":"windows_exporter","channel":"Application","computer":"prod-00000X","event_id":102,"level":2,"levelText":"Error","opCodeText":"Info","keywords":"Classic","timeCreated":"2022-09-22T19:31:49.816165100Z","eventRecordID":1003,"message":"collector iis failed after 0.001985s: counter not found"}
{"source":"windows_exporter","channel":"Application","computer":"prod-00000X","event_id":102,"level":2,"levelText":"Error","opCodeText":"Info","keywords":"Classic","timeCreated":"2022-09-22T19:31:49.815562800Z","eventRecordID":1002,"message":"collector iis failed after 0.001985s: counter not found"}
{"source":"windows_exporter","channel":"Application","computer":"prod-00000X","event_id":102,"level":2,"levelText":"Error","opCodeText":"Info","keywords":"Classic","timeCreated":"2022-09-22T19:31:49.815366000Z","eventRecordID":1001,"message":"failed collecting iis metrics:\u003cnil\u003e counter not found"}
{"source":"windows_exporter","channel":"Application","computer":"prod-00000X","event_id":102,"level":2,"levelText":"Error","opCodeText":"Info","keywords":"Classic","timeCreated":"2022-09-22T19:31:49.814088600Z","eventRecordID":1000,"message":"failed collecting iis metrics:\u003cnil\u003e counter not found"}
{"source":"windows_exporter","channel":"Application","computer":"prod-00000X","event_id":102,"level":2,"levelText":"Error","opCodeText":"Info","keywords":"Classic","timeCreated":"2022-09-22T19:31:49.813402200Z","eventRecordID":999,"message":"collector cpu failed after 0.000000s: counter not found"}
{"source":"windows_exporter","channel":"Application","computer":"prod-00000X","event_id":102,"level":2,"levelText":"Error","opCodeText":"Info","keywords":"Classic","timeCreated":"2022-09-22T19:31:49.812894000Z","eventRecordID":998,"message":"collector cpu failed after 0.000000s: counter not found"}
```

**Comment by breed808** [comment] 2022-09-23 21:08
I'm not entirely certain this is an issue with the exporter: it's stating that required counters from Perflib cannot be found.

Are the counters present when querying Perflib with `Get-Counter`? E.G `(Get-Counter -ListSet 'Processor Information').Counter` to list the available counters for the `cpu` collector.

**Comment by DaveOHenry** [comment] 2022-09-26 07:09
Thanks for the info. Unfortunately I can't reproduce this currently. It was only happening on a single vm. The error was resolved by rebooting the instance in question.

**Closed** 2023-02-04 01:53 UTC
Labels: collector/iis
