### ISSUE TITLE
Failed collect metrics while IIS not responding

### ISSUE THREAD

**Issue by majordhote** [prometheus-community/windows_exporter#1124] opened 2023-01-23 08:32 UTC
Hi,

Failed to retrieve all metrics when IIS is not responding on the server and the collector is enabled.

Testing with a curl commande returns an error and all other metrics are not retrieve : 
`An error has occurred while serving metrics:

37 error(s) occurred:
* collected metric "windows_iis_current_anonymous_users" { label:<name:"site" value:"EnvTest" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_current_blocked_async_io_requests" { label:<name:"site" value:"EnvTest" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_current_cgi_requests" { label:<name:"site" value:"EnvTest" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_current_connections" { label:<name:"site" value:"EnvTest" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_current_isapi_extension_requests" { label:<name:"site" value:"EnvTest" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_current_non_anonymous_users" { label:<name:"site" value:"EnvTest" > gauge:<value:19 > } was collected before with the same name and label values
[...]`

If getting metrics from a collector failed, maybe it will be good to get the other ones ?

**Comment by breed808** [comment] 2023-02-04 01:41
Duplicate of  #1009

**Closed by breed808** 2023-02-04 01:41 UTC
Labels: duplicate
