### ISSUE TITLE
The mssql collector of windows_exporter cannot display the version number of sqlserver

### ISSUE THREAD

**Issue by ilanni2460** [prometheus-community/windows_exporter#1606] opened 2024-09-04 01:07 UTC
### Current Behavior

The mssql collector of windows_exporter cannot display the version number of sqlserver

### Expected Behavior

The mssql collector of windows_exporter cannot display the version number of sqlserver

### Environment

- windows_exporter Version: all Version
- Windows Server Version: windows server 2016/2019/2022

### windows_exporter logs

```shell
no
```

**Comment by DiniFarb** [comment] 2024-09-04 09:40
Have a look on the discussion at #1527 - You can use the textfile collector for the MSSQL version.

**Comment by jkroepke** [comment] 2024-09-04 19:35
duplicate of https://github.com/prometheus-community/windows_exporter/issues/1527

**Closed by jkroepke** 2024-09-04 19:35 UTC
Labels: 🐞 bug
