### ISSUE TITLE
As soon as I add iis in a template - Err was collected before with the same name and label values

### ISSUE THREAD

**Issue by eliassal** [prometheus-community/windows_exporter#932] opened 2022-01-27 18:28 UTC
Hi, I have copied the config sample as follows (the exec not mis on command line)

---
```
# Note this is not an exhaustive list of all configuration values
collectors:
  enabled: cpu,iis
collector:
  service:
    services-where: Name='windows_exporter'
log:
  level: debug
scrape:
  timeout-margin: 0.5
telemetry:
  addr: ":9182"
  path: /metrics
  max-requests: 5
```

When I visit http://localhost:9182/metrics,  I have so many errors as follows

> was collected before with the same name and label values

**Comment by zpf2022** [comment] 2022-01-28 12:14
#903

**Comment by breed808** [comment] 2022-01-31 07:08
Yes, this is a duplicate of #903, which will be resolved in the next release.

**Closed by breed808** 2022-01-31 07:08 UTC
Labels: duplicate, collector/iis

**Comment by MarNicGit** [comment] 2022-03-23 12:13
Sorry for re-opening this, but I'm still experiencing this issue on 18.1, running on Windows Server 2022 21H2 (OS build 20348.502). I first got this issue on 18.0, so I figured I'd update, but the issue is still there. Running the amd64 build.

Enabled collectors: [defaults],iis,memory,mssql

Errors:

```
An error has occurred while serving metrics:

36 error(s) occurred:
* collected metric "windows_iis_current_anonymous_users" { label:<name:"site" value:"api.contoso.com" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_current_blocked_async_io_requests" { label:<name:"site" value:"api.contoso.com" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_current_cgi_requests" { label:<name:"site" value:"api.contoso.com" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_current_connections" { label:<name:"site" value:"api.contoso.com" > gauge:<value:3 > } was collected before with the same name and label values
* collected metric "windows_iis_current_isapi_extension_requests" { label:<name:"site" value:"api.contoso.com" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_current_non_anonymous_users" { label:<name:"site" value:"api.contoso.com" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_received_bytes_total" { label:<name:"site" value:"api.contoso.com" > counter:<value:7.13864547e+08 > } was collected before with the same name and label values
* collected metric "windows_iis_sent_bytes_total" { label:<name:"site" value:"api.contoso.com" > counter:<value:7.4774441163e+10 > } was collected before with the same name and label values
* collected metric "windows_iis_anonymous_users_total" { label:<name:"site" value:"api.contoso.com" > counter:<value:1.038936e+06 > } was collected before with the same name and label values
* collected metric "windows_iis_blocked_async_io_requests_total" { label:<name:"site" value:"api.contoso.com" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_cgi_requests_total" { label:<name:"site" value:"api.contoso.com" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_connection_attempts_all_instances_total" { label:<name:"site" value:"api.contoso.com" > counter:<value:830255 > } was collected before with the same name and label values
* collected metric "windows_iis_files_received_total" { label:<name:"site" value:"api.contoso.com" > counter:<value:8 > } was collected before with the same name and label values
* collected metric "windows_iis_files_sent_total" { label:<name:"site" value:"api.contoso.com" > counter:<value:60 > } was collected before with the same name and label values
* collected metric "windows_iis_ipapi_extension_requests_total" { label:<name:"site" value:"api.contoso.com" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_locked_errors_total" { label:<name:"site" value:"api.contoso.com" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_logon_attempts_total" { label:<name:"site" value:"api.contoso.com" > counter:<value:1.038937e+06 > } was collected before with the same name and label values
* collected metric "windows_iis_non_anonymous_users_total" { label:<name:"site" value:"api.contoso.com" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_not_found_errors_total" { label:<name:"site" value:"api.contoso.com" > counter:<value:643 > } was collected before with the same name and label values
* collected metric "windows_iis_rejected_async_io_requests_total" { label:<name:"site" value:"api.contoso.com" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"other" > label:<name:"site" value:"api.contoso.com" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"COPY" > label:<name:"site" value:"api.contoso.com" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"DELETE" > label:<name:"site" value:"api.contoso.com" > counter:<value:782 > } was collected before with the same name and label values
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"GET" > label:<name:"site" value:"api.contoso.com" > counter:<value:478473 > } was collected before with the same name and label values
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"HEAD" > label:<name:"site" value:"api.contoso.com" > counter:<value:31 > } was collected before with the same name and label values
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"LOCK" > label:<name:"site" value:"api.contoso.com" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"MKCOL" > label:<name:"site" value:"api.contoso.com" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"MOVE" > label:<name:"site" value:"api.contoso.com" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"OPTIONS" > label:<name:"site" value:"api.contoso.com" > counter:<value:44182 > } was collected before with the same name and label values
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"POST" > label:<name:"site" value:"api.contoso.com" > counter:<value:605656 > } was collected before with the same name and label values
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"PROPFIND" > label:<name:"site" value:"api.contoso.com" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"PROPPATCH" > label:<name:"site" value:"api.contoso.com" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"PUT" > label:<name:"site" value:"api.contoso.com" > counter:<value:8 > } was collected before with the same name and label values
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"SEARCH" > label:<name:"site" value:"api.contoso.com" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"TRACE" > label:<name:"site" value:"api.contoso.com" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_requests_total" { label:<name:"method" value:"UNLOCK" > label:<name:"site" value:"api.contoso.com" > counter:<value:0 > } was collected before with the same name and label values
```

(real site replaced with placeholder)

**Comment by breed808** [comment] 2022-04-06 10:33
Does the issue occur in previous versions? It'd be helpful to know when your issue was introduced into the codebase.
If you can, have a look at #903 for some debugging steps that others applied to the issue. Unfortunately I'm not overly familiar with IIS, so I can only be of so much help :disappointed:

**Comment by MarNicGit** [comment] 2022-04-08 09:43
I've downgraded a couple times and found the following:
- 17.1: 612 errors
- 17.0: 612 errors
- 16.0: All is good!

Looks like whatever broke between 16 and 17 only got partially fixed in 18, and I'm saying that based on the amount of errors I'm getting (612 on 17.x, 32 on 18.x) I _suspect_ it has something to do with the switch from WMI to PerfLib in #831, but in all honestly I don't know enough about Perflib or Go to be sure.

I'll spin up some server 2012, 2016 and 2019 VM's this weekend to further isolate this issue, since 2022 bumped the IIS version up from 10.0.17763 to 10.0.20303.1.
