### ISSUE TITLE
Metrics Endpoint: Encountering error for windows_terminal_services

### ISSUE THREAD

**Issue by msadmire** [prometheus-community/windows_exporter#1196] opened 2023-04-24 19:51 UTC
Upon visiting the exposed `/metrics` endpoint, I'm encountering the errors seen below.
The exporter has been running on this production-facing machine for some time now, and only recently had I noticed that metrics were missing due to the errors.

```
An error has occurred while serving metrics:

15 error(s) occurred:
* collected metric "windows_terminal_services_handles" { label:<name:"session_name" value:"RDP-Tcp 6" > gauge:<value:6773 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_page_fault_total" { label:<name:"session_name" value:"RDP-Tcp 6" > counter:<value:439106 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_page_file_bytes" { label:<name:"session_name" value:"RDP-Tcp 6" > gauge:<value:2.1553152e+08 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_page_file_bytes_peak" { label:<name:"session_name" value:"RDP-Tcp 6" > gauge:<value:2.39792128e+08 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_privileged_time_seconds_total" { label:<name:"session_name" value:"RDP-Tcp 6" > counter:<value:0.6898432 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_processor_time_seconds_total" { label:<name:"session_name" value:"RDP-Tcp 6" > counter:<value:1.5156245 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_user_time_seconds_total" { label:<name:"session_name" value:"RDP-Tcp 6" > counter:<value:0.8257808999999999 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_pool_non_paged_bytes" { label:<name:"session_name" value:"RDP-Tcp 6" > gauge:<value:356848 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_pool_paged_bytes" { label:<name:"session_name" value:"RDP-Tcp 6" > gauge:<value:4.380568e+06 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_private_bytes" { label:<name:"session_name" value:"RDP-Tcp 6" > gauge:<value:2.1553152e+08 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_threads" { label:<name:"session_name" value:"RDP-Tcp 6" > gauge:<value:151 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_virtual_bytes" { label:<name:"session_name" value:"RDP-Tcp 6" > gauge:<value:3.3052767367168e+13 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_virtual_bytes_peak" { label:<name:"session_name" value:"RDP-Tcp 6" > gauge:<value:3.305396246528e+13 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_working_set_bytes" { label:<name:"session_name" value:"RDP-Tcp 6" > gauge:<value:5.69716736e+08 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_working_set_bytes_peak" { label:<name:"session_name" value:"RDP-Tcp 6" > gauge:<value:6.18242048e+08 > } was collected before with the same name and label values
```

Any tips or advice? TIA

**Comment by 5E7EN** [comment] 2023-06-12 18:23
Did you ever figure out a solution to this?

**Comment by breed808** [comment] 2023-08-20 03:38
Duplicate of #1086. Have a look at my comment there and see if you can provide me with the requested info.

**Closed by breed808** 2023-08-20 03:38 UTC
Labels: duplicate, collector/terminal services
