### ISSUE TITLE
mssql collector does not start with waitstats class enabled

### ISSUE THREAD

**Issue by cdestouni-fmp** [prometheus-community/windows_exporter#888] opened 2021-12-16 17:04 UTC
Windows mssql collector is enabled and starts successfully based on the endpoint info below. However it seems to be missing the waitstats class. Is it meant to be this way or is this an issue? The docs suggest that this is enabled when the mssql collector is enabled in the config file.

```
# HELP windows_mssql_collector_success windows_exporter: Whether a mssql child collector was successful.
# TYPE windows_mssql_collector_success gauge
windows_mssql_collector_success{collector="accessmethods",mssql_instance="MSSQLSERVER"} 1
windows_mssql_collector_success{collector="availreplica",mssql_instance="MSSQLSERVER"} 1
windows_mssql_collector_success{collector="bufman",mssql_instance="MSSQLSERVER"} 1
windows_mssql_collector_success{collector="databases",mssql_instance="MSSQLSERVER"} 1
windows_mssql_collector_success{collector="dbreplica",mssql_instance="MSSQLSERVER"} 1
windows_mssql_collector_success{collector="genstats",mssql_instance="MSSQLSERVER"} 1
windows_mssql_collector_success{collector="locks",mssql_instance="MSSQLSERVER"} 1
windows_mssql_collector_success{collector="memmgr",mssql_instance="MSSQLSERVER"} 1
windows_mssql_collector_success{collector="sqlerrors",mssql_instance="MSSQLSERVER"} 1
windows_mssql_collector_success{collector="sqlstats",mssql_instance="MSSQLSERVER"} 1
windows_mssql_collector_success{collector="transactions",mssql_instance="MSSQLSERVER"} 1
```
Im using the version below. 
```
windows_exporter_build_info{branch="master",goversion="go1.15.6",revision="f316d81d50738eb0410b0748c5dcdc6874afe95a",version="0.16.0"} 1
```

**Comment by breed808** [comment] 2021-12-19 10:15
This sounds like a bug. Is the exporter providing any relevant output in the event viewer?

**Comment by dcop7** [comment] 2021-12-20 08:13
It is not a bug. That feature isn't in the release yet.
The commit was done on Jun 29: https://github.com/prometheus-community/windows_exporter/commit/1b96bb6d083f1bfd454ffc6a98a697cf970dfc24#diff-2f0ab6ba004a8d6a2772bcf8d075132301275c303a7493584435b63196604617

The latest release (v0.16.0) was on Feb 25.

Until a new version is released, that feature isn't available.

Someone already open a issue requesting a new release (https://github.com/prometheus-community/windows_exporter/issues/854) but nothing yet...

**Comment by breed808** [comment] 2021-12-20 21:53
Thanks @dcop7, I was looking through `master` and not the most recent release.

I'm looking to cut a new release soon, but work and the holiday season may delay this until the new year when I have some free time.

**Comment by Wittionary** [comment] 2022-01-21 04:38
@breed808 Is there a way to tag issues as "solved in version x" or "resolved in a coming release"?

**Comment by breed808** [comment] 2022-01-26 21:56
Milestones were the first feature that came to mind, but that's more for progress tracking than issue tagging. Tracking with comments as we've previously done, or a "fixed in master" tag may work.

I'll close this issue as a new release has been made available.

**Closed by breed808** 2022-01-26 21:56 UTC
Labels: bug, collector/mssql

**Comment by Wittionary** [comment] 2022-01-26 22:11
Thanks! I'm looking to make myself more helpful to the Prometheus community - without learning golang 😅 - and I thought reducing the backlog of issues, even if by management, would help.

**Comment by breed808** [comment] 2022-01-26 22:13
Thanks, more help is always wanted :smile:
